services:
 rabbitmq:
    container_name: rabbitmq_temperature
    image: rabbitmq:3.12-management-alpine
    volumes:
      - "./rabbit_data:/var/lib/rabbitmq/"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234